//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;fileFormatVersion&quot;: 1,
        ///  &quot;identifier&quot;: &quot;DirectionalCoupler&quot;,
        ///  &quot;nazcaFunctionParameters&quot;: &quot;deltaLength = 50&quot;,
        ///  &quot;nazcaFunctionName&quot;: &quot;placeCell_DirectionalCoupler&quot;,
        ///  &quot;sceneResPath&quot;: &quot;res://Scenes/Components/DirectionalCoupler/DirectionalCouplerScene.tscn&quot;,
        ///  &quot;deltaLength&quot;: 0.5,
        ///  &quot;widthInTiles&quot;: 2,
        ///  &quot;heightInTiles&quot;: 2,
        ///  &quot;pins&quot;: [
        ///	{
        ///	  &quot;number&quot;: 0,
        ///	  &quot;name&quot;: &quot;west0&quot;,
        ///	  &quot;matterType&quot;: 1,
        ///	  &quot;side&quot;: 2,
        ///	  &quot;partX&quot;: 0,
        ///	  &quot;partY&quot;: 0
        ///	},
        ///	{
        ///	  &quot;number&quot;: 1,
        ///	  &quot;name&quot;: &quot;east0&quot;,
        ///	  &quot;matterType&quot;: 1,
        ///	  &quot;sid [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DirectionalCouplerDraft {
            get {
                return ResourceManager.GetString("DirectionalCouplerDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///    &quot;fileFormatVersion&quot;: 1,
        ///    &quot;identifier&quot;: &quot;Straight&quot;,
        ///    &quot;nazcaFunctionParameters&quot;: &quot;&quot;,
        ///    &quot;nazcaFunctionName&quot;: &quot;placeCell_StraightWG&quot;,
        ///    &quot;sceneResPath&quot;: &quot;res://Scenes/Components/Straight/StraightWaveGuide.tscn&quot;,
        ///    &quot;deltaLength&quot;: 0,
        ///    &quot;widthInTiles&quot;: 1,
        ///    &quot;heightInTiles&quot;: 1,
        ///    &quot;pins&quot;: [
        ///        {
        ///            &quot;number&quot;: 0,
        ///            &quot;name&quot;: &quot;west&quot;,
        ///            &quot;matterType&quot;: 1,
        ///            &quot;side&quot;: 2,
        ///            &quot;partX&quot;: 0,
        ///            &quot;partY&quot;: 0
        ///        },
        ///        {
        ///            &quot;number&quot;: 1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string StraightWG {
            get {
                return ResourceManager.GetString("StraightWG", resourceCulture);
            }
        }
    }
}
