//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAP_Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     return fullLayoutInner
        ///
        ///nd.print_warning = False
        ///nd.export_gds(topcells=FullDesign(&quot;Akhetonics_ConnectAPIC&quot;), filename=&quot;ReplaceThisFileName.gds&quot;)
        ///.
        /// </summary>
        public static string NazcaFooter {
            get {
                return ResourceManager.GetString("NazcaFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import nazca as nd
        ///from TestPDK import TestPDK
        ///
        ///CAPICPDK = TestPDK()
        ///
        ///def FullDesign(layoutName):
        ///    with nd.Cell(name=layoutName) as fullLayoutInner:
        ///
        ///        grating1 = CAPICPDK.placeGratingArray_East(8).put(0, 0)
        ///        grating2 = CAPICPDK.placeGratingArray_West(8).put(CAPICPDK._CellSize * 24, 0)
        ///.
        /// </summary>
        public static string NazcaHeader {
            get {
                return ResourceManager.GetString("NazcaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akhetonics_ConnectAPIC.
        /// </summary>
        public static string NazcaLayoutName {
            get {
                return ResourceManager.GetString("NazcaLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPICPDK.
        /// </summary>
        public static string NazcaPDKName {
            get {
                return ResourceManager.GetString("NazcaPDKName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grating1.
        /// </summary>
        public static string NazcaStandardLeftInputCellName {
            get {
                return ResourceManager.GetString("NazcaStandardLeftInputCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grating2.
        /// </summary>
        public static string NazcaStandardRightInputCellName {
            get {
                return ResourceManager.GetString("NazcaStandardRightInputCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import nazca as nd
        ///import math
        ///from nazca.interconnects import Interconnect
        ///
        ///class TestPDK(object):
        ///
        ///    # Singleton
        ///    def __new__(cls):
        ///        if not hasattr(cls, &apos;instance&apos;):
        ///            cls.instance = super(TestPDK, cls).__new__(cls)
        ///        return cls.instance
        ///    
        ///    def __init__(self):
        ///        # General 
        ///        self._BendRadius = 80
        ///        self._WGWidth = 1.2
        ///        self._CouplerSpacing = 0.35
        ///        self._CrossOver = 50
        ///        self._CellSize = 250        # Has to be a multiple of the Fiber A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PDK {
            get {
                return ResourceManager.GetString("PDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestPDK.py.
        /// </summary>
        public static string PDKFileName {
            get {
                return ResourceManager.GetString("PDKFileName", resourceCulture);
            }
        }
    }
}
