//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_Core {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAP_Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///nd.print_warning = False
        ///nd.export_gds(topcells=FullDesign(&quot;Akhetonics_ConnectAPIC&quot;), filename=&quot;ReplaceThisFileName.gds&quot;)
        /// ähnelt.
        /// </summary>
        public static string NazcaFooter {
            get {
                return ResourceManager.GetString("NazcaFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import nazca as nd
        ///from TestPDK import TestPDK
        ///
        ///CAPICPDK = TestPDK()
        ///
        ///def FullDesign(layoutName):
        ///    with nd.Cell(name=layoutName) as fullLayoutInner:       
        ///
        ///        grating = CAPICPDK.placeGratingArray_East(8).put(0, 0)
        /// ähnelt.
        /// </summary>
        public static string NazcaHeader {
            get {
                return ResourceManager.GetString("NazcaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Akhetonics_ConnectAPIC ähnelt.
        /// </summary>
        public static string NazcaLayoutName {
            get {
                return ResourceManager.GetString("NazcaLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAPICPDK ähnelt.
        /// </summary>
        public static string NazcaPDKName {
            get {
                return ResourceManager.GetString("NazcaPDKName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grating ähnelt.
        /// </summary>
        public static string NazcaStandardInputCellName {
            get {
                return ResourceManager.GetString("NazcaStandardInputCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import nazca as nd
        ///
        ///class TestPDK(object):
        ///
        ///    # Singleton
        ///    def __new__(cls):
        ///        if not hasattr(cls, &apos;instance&apos;):
        ///            cls.instance = super(TestPDK, cls).__new__(cls)
        ///        return cls.instance
        ///    
        ///    def __init__(self):
        ///        # General 
        ///        self._BendRadius = 80  
        ///        self._WGWidth = 1.2    
        ///        self._CellSize = 250            
        ///        self._GratingOffset = self._CellSize        
        ///        self._SiNLayer = 1
        ///        self._BoxLayer = 1001
        ///        self._TextLayer = 1002
        ///
        ///    de [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string PDK {
            get {
                return ResourceManager.GetString("PDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TestPDK.py ähnelt.
        /// </summary>
        public static string PDKFileName {
            get {
                return ResourceManager.GetString("PDKFileName", resourceCulture);
            }
        }
    }
}
