import nazca as nd
from TestPDK import TestPDK

CAPICPDK = TestPDK()

def FullDesign(layoutName):
    with nd.Cell(name=layoutName) as fullLayoutInner:       

        grating = CAPICPDK.placeGratingArray_East(8).put(0, 0)
        cell_0_2 = CAPICPDK.placeCell_StraightWG().put('west', grating.pin['io0'])
        cell_1_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_0_2.pin['east'])
        cell_2_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_1_2.pin['east'])
        cell_3_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_2_2.pin['east'])
        cell_4_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_3_2.pin['east'])
        cell_5_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_4_2.pin['east'])
        cell_6_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_5_2.pin['east'])
        cell_7_2 = CAPICPDK.placeCell_MMI3x3().put('west0', cell_6_2.pin['east'])
        cell_4_3 = CAPICPDK.placeCell_MMI3x3().put('west2', cell_7_2.pin['west1'])
        cell_1_3 = CAPICPDK.placeCell_MMI3x3().put('east0', cell_4_3.pin['east2'])
        cell_0_3 = CAPICPDK.placeCell_StraightWG().put('east', cell_1_3.pin['west0'])
        cell_0_4 = CAPICPDK.placeCell_StraightWG().put('east', cell_1_3.pin['west1'])
        cell_0_5 = CAPICPDK.placeCell_StraightWG().put('east', cell_1_3.pin['west2'])
        cell_7_5 = CAPICPDK.placeCell_StraightWG().put('east', cell_4_3.pin['west0'])
        cell_8_5 = CAPICPDK.placeCell_StraightWG().put('east', cell_7_5.pin['west'])
        cell_9_5 = CAPICPDK.placeCell_StraightWG().put('east', cell_8_5.pin['west'])
        cell_10_3 = CAPICPDK.placeCell_MMI3x3().put('west2', cell_9_5.pin['west'])
        cell_13_3 = CAPICPDK.placeCell_MMI3x3().put('west0', cell_10_3.pin['east0'])
        cell_16_3 = CAPICPDK.placeCell_MMI3x3().put('west0', cell_13_3.pin['east0'])
        cell_19_3 = CAPICPDK.placeCell_BendWG().put('west', cell_16_3.pin['east0'])
        cell_19_4 = CAPICPDK.placeCell_BendWG().put('west', cell_19_3.pin['south'])
        cell_19_5 = CAPICPDK.placeCell_BendWG().put('west', cell_16_3.pin['east2'])
        cell_19_6 = CAPICPDK.placeCell_StraightWG().put('west', cell_19_5.pin['south'])
        cell_19_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_19_6.pin['east'])
        cell_17_8 = CAPICPDK.placeCell_MMI3x3().put('east2', cell_19_7.pin['east'])
        cell_18_7 = CAPICPDK.placeCell_BendWG().put('south', cell_17_8.pin['east1'])
        cell_17_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_18_7.pin['west'])
        cell_16_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_17_7.pin['east'])
        cell_15_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_16_7.pin['east'])
        cell_14_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_15_7.pin['east'])
        cell_13_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_14_7.pin['east'])
        cell_12_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_13_7.pin['east'])
        cell_11_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_12_7.pin['east'])
        cell_8_6 = CAPICPDK.placeCell_MMI3x3().put('east1', cell_11_7.pin['east'])
        cell_5_6 = CAPICPDK.placeCell_MMI3x3().put('east0', cell_8_6.pin['west0'])
        cell_2_6 = CAPICPDK.placeCell_MMI3x3().put('east0', cell_5_6.pin['west0'])
        cell_1_7 = CAPICPDK.placeCell_BendWG().put('south', cell_2_6.pin['west1'])
        cell_1_8 = CAPICPDK.placeCell_BendWG().put('south', cell_1_7.pin['west'])
        cell_11_8 = CAPICPDK.placeCell_MMI3x3().put('west0', cell_8_6.pin['east2'])
        cell_8_9 = CAPICPDK.placeCell_MMI3x3().put('east0', cell_11_8.pin['west1'])
        cell_5_9 = CAPICPDK.placeCell_MMI3x3().put('east0', cell_8_9.pin['west0'])
        cell_2_9 = CAPICPDK.placeCell_MMI3x3().put('east0', cell_5_9.pin['west0'])
        cell_14_8 = CAPICPDK.placeCell_MMI3x3().put('west0', cell_11_8.pin['east0'])
        cell_19_11 = CAPICPDK.placeCell_BendWG().put('south', cell_17_8.pin['west2'])
        cell_20_11 = CAPICPDK.placeCell_BendWG().put('south', cell_19_11.pin['west'])
        cell_20_10 = CAPICPDK.placeCell_StraightWG().put('west', cell_20_11.pin['west'])
        cell_20_9 = CAPICPDK.placeCell_StraightWG().put('west', cell_20_10.pin['east'])
        cell_20_8 = CAPICPDK.placeCell_StraightWG().put('west', cell_20_9.pin['east'])
        cell_20_7 = CAPICPDK.placeCell_StraightWG().put('west', cell_20_8.pin['east'])
        cell_20_6 = CAPICPDK.placeCell_StraightWG().put('east', cell_20_7.pin['east'])
        cell_20_5 = CAPICPDK.placeCell_StraightWG().put('east', cell_20_6.pin['west'])
        cell_20_4 = CAPICPDK.placeCell_StraightWG().put('east', cell_20_5.pin['west'])
        cell_20_3 = CAPICPDK.placeCell_StraightWG().put('east', cell_20_4.pin['west'])
        cell_20_2 = CAPICPDK.placeCell_BendWG().put('south', cell_20_3.pin['west'])
        cell_19_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_20_2.pin['west'])
        cell_18_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_19_2.pin['east'])
        cell_17_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_18_2.pin['east'])
        cell_16_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_17_2.pin['east'])
        cell_15_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_16_2.pin['east'])
        cell_14_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_15_2.pin['east'])
        cell_13_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_14_2.pin['east'])
        cell_12_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_13_2.pin['east'])
        cell_11_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_12_2.pin['east'])
        cell_10_2 = CAPICPDK.placeCell_StraightWG().put('west', cell_11_2.pin['east'])
    return fullLayoutInner

nd.print_warning = False
nd.export_gds(topcells=FullDesign("Akhetonics_ConnectAPIC"), filename="TestPDK.py")
